In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# import torch
# from torch.autograd import Variable

In [2]:
means = [[2, 2], [8, 3], [3, 6]]
cov = [[1, 0], [0, 1]]
N = 500
X0 = np.random.multivariate_normal(means[0], cov, N)
X1 = np.random.multivariate_normal(means[1], cov, N)
X2 = np.random.multivariate_normal(means[2], cov, N)

X0, X0.shape

(array([[ 4.67911695e+00,  3.48269619e+00],
        [ 2.97158761e+00,  8.18947017e-01],
        [ 2.22343108e+00,  2.69609211e+00],
        [ 1.02173257e+00,  2.02636141e+00],
        [ 1.80192082e+00, -1.06141430e+00],
        [ 3.15081813e+00,  2.90755914e+00],
        [ 2.93209221e+00,  4.52266104e+00],
        [ 1.67318839e+00,  1.03123664e+00],
        [ 2.37505852e+00,  1.37978372e+00],
        [ 1.41334457e+00,  2.12352879e+00],
        [ 1.17527683e+00,  2.43601176e+00],
        [ 1.14401613e+00,  1.91801502e+00],
        [ 1.26919112e+00,  2.69431788e+00],
        [ 2.11411770e+00,  1.84333159e+00],
        [ 3.12917044e+00,  2.60166413e+00],
        [ 3.09374180e+00,  1.51919500e+00],
        [ 3.12117604e+00,  1.97570341e+00],
        [ 3.25631465e-01,  2.65685591e+00],
        [ 1.97865494e+00,  3.73231935e+00],
        [ 1.85789478e+00,  3.09963141e+00],
        [ 1.61424210e+00,  3.85793240e-01],
        [ 3.99137913e+00,  1.90281641e+00],
        [ 8.11426860e-01,  2.483

In [3]:
# each column is a datapoint
X = np.concatenate((X0, X1, X2), axis = 0).T 
X, X.shape

(array([[4.67911695, 2.97158761, 2.22343108, ..., 3.97298871, 0.8455229 ,
         2.5052276 ],
        [3.48269619, 0.81894702, 2.69609211, ..., 5.82379766, 5.68124509,
         6.33471402]]),
 (2, 1500))

In [4]:
# extended data
X = np.concatenate((np.ones((1, 3*N)), X), axis = 0)
C = 3
X, X.shape

(array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
         1.        ],
        [4.67911695, 2.97158761, 2.22343108, ..., 3.97298871, 0.8455229 ,
         2.5052276 ],
        [3.48269619, 0.81894702, 2.69609211, ..., 5.82379766, 5.68124509,
         6.33471402]]),
 (3, 1500))

In [5]:
original_label = np.asarray([0]*N + [1]*N + [2]*N).T
original_label, original_label.shape

(array([0, 0, 0, ..., 2, 2, 2]), (1500,))